// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWamGI9A-CMWhBNi-YEyUUPSKwlZN5Sw',
    appId: '1:989932473731:web:1da039c73461f62bc37ab6',
    messagingSenderId: '989932473731',
    projectId: 'athlete-workload-app',
    authDomain: 'athlete-workload-app.firebaseapp.com',
    storageBucket: 'athlete-workload-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHeJSKNUu5nwUnQqP2-8S88ouiW1GvGU',
    appId: '1:989932473731:android:91c4758f3c389edbc37ab6',
    messagingSenderId: '989932473731',
    projectId: 'athlete-workload-app',
    storageBucket: 'athlete-workload-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFD07dBn-5jIseSyUGM3otnCREYggfJkc',
    appId: '1:989932473731:ios:923a63a18a3d2583c37ab6',
    messagingSenderId: '989932473731',
    projectId: 'athlete-workload-app',
    storageBucket: 'athlete-workload-app.firebasestorage.app',
    iosClientId: '989932473731-p6rthmrf417gab9shr1dqmhj7cun9mfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.athleteWorkload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFD07dBn-5jIseSyUGM3otnCREYggfJkc',
    appId: '1:989932473731:ios:923a63a18a3d2583c37ab6',
    messagingSenderId: '989932473731',
    projectId: 'athlete-workload-app',
    storageBucket: 'athlete-workload-app.firebasestorage.app',
    iosClientId: '989932473731-p6rthmrf417gab9shr1dqmhj7cun9mfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.athleteWorkload',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWamGI9A-CMWhBNi-YEyUUPSKwlZN5Sw',
    appId: '1:989932473731:web:3170512c903366c4c37ab6',
    messagingSenderId: '989932473731',
    projectId: 'athlete-workload-app',
    authDomain: 'athlete-workload-app.firebaseapp.com',
    storageBucket: 'athlete-workload-app.firebasestorage.app',
  );

}